# -*- coding: utf-8 -*-
"""project106.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gaD6H4fdkVTyqHjeuwm8OHFcFbnccGU0
"""

import csv
import numpy as np

def getDataSource(data_path):
  marks=[]
  dayspresent=[]
  with open(data_path)as csv_file:
    csv_reader=csv.DictReader(csv_file)
    for row in csv_reader:
      marks.append(float(row["Marks In Percentage"]))
      dayspresent.append(float(row["Days Present"]))
  return{"x":marks,"y":dayspresent}

def correlation(datasource):
  correlation=np.corrcoef(datasource["x"],datasource["y"])
  print("correlation is /n--->",correlation[0,1])

def setup():
  data_path="data.csv"
  datasource=getDataSource(data_path)
  correlation(datasource)

setup()